import type { Tour, Review } from '@/types'

export const mockTours: Tour[] = [
  // ── 활성 상품 ──────────────────────────────────────────────
  {
    id: '1',
    title: '한강 바이크투어',
    title_en: 'Han River Bike Tour',
    slug: 'hangang-healing-tour',
    description:
      '자전거 전문가들이 직접 달려보며 설계한 한강 힐링 코스. 당산역에서 출발해 샛강 생태공원을 지나, 반포대교 분수 포인트에서 감동을 느끼고, 한강라면으로 에너지 보충 후 여의도까지 달리는 프리미엄 순환 투어입니다. 일반 자전거 / MTB·로드 / 전기자전거 중 원하는 스타일로 선택하세요.',
    short_description: '당산역 출발 · 샛강·반포·여의도 순환 · 3~4시간 · 자전거 3종 선택',
    category: 'city',
    difficulty: 'easy',
    duration_hours: 3.5,
    distance_km: 21.2,
    max_participants: 50,
    price_krw: 50000,
    price_usd: 38,
    thumbnail_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
      'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=1200&q=80',
      'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=1200&q=80',
    ],
    meeting_point: '당산역 2번 출구 (Dangsan Station, Exit 2)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    includes: [
      '자전거 1대 (로드 / MTB / 전기자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '위치추적 장치',
      '도난 방지 알람',
      '한강라면 (반포대교 포인트)',
    ],
    excludes: [
      '전문 가이드 (선택 추가, +₩100,000 / 최대 10인)',
      '여행자 보험 (선택 추가, ₩10,000 이하)',
      '서울의 달 기구 탑승권 (현장 구매 가능)',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      '당산역 출발 → 샛강 생태공원 (도심 속 자연)',
      '한강대교 → 반포대교 분수 뷰포인트',
      '한강라면 포인트 (중간 휴식)',
      '노량대교 → 여의도 한강공원',
      '서울의 달 기구 탑승 가능 (현장 개별 구매)',
      '블랙박스로 녹화된 나만의 투어 영상 제공',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-05-01T00:00:00Z',
    updated_at: '2026-05-30T00:00:00Z',
  },

  // ── 활성 상품 ─────────────────────────────────────────────
  {
    id: '4',
    title: '한강 아라뱃길 바이크투어',
    title_en: 'Han River Ara Waterway Bike Tour',
    slug: 'ara-waterway-tour',
    description:
      '당산역에서 출발해 서울식물원, 경인아라뱃길을 따라 아라마루 전망대, 정서진(서해)까지 달리는 장거리 코스. 도심 한강에서 서해까지 이어지는 특별한 라이딩 경험. 왕복(34.5km)과 편도(34.5km, 용달비 별도) 중 선택 가능합니다.',
    short_description: '당산역 출발 · 서울식물원·아라뱃길·정서진(서해) · 왕복/편도 선택',
    category: 'city',
    difficulty: 'moderate',
    duration_hours: 7,
    distance_km: 69,
    max_participants: 50,
    price_krw: 70000,
    price_usd: 53,
    thumbnail_url: '/stop-ara-waterfall.png',
    images: [
      '/stop-ara-dangsan.png',
      '/stop-ara-botanic.png',
      '/stop-ara-port.png',
      '/stop-ara-tower.png',
      '/stop-ara-waterfall.png',
      '/stop-ara-bikeway.png',
      '/stop-ara-jeongseojin.png',
      '/stop-jeongseojin.png',
    ],
    meeting_point: '당산역 2번 출구 (Dangsan Station, Exit 2)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    options: [
      {
        id: 'roundtrip',
        label: '왕복',
        label_en: 'Round Trip',
        description: '당산역 출발 → 정서진 → 당산역 복귀 · 69km',
        price_modifier_krw: 0,
        duration_hours: 7,
      },
      {
        id: 'oneway',
        label: '편도',
        label_en: 'One Way',
        description: '당산역 출발 → 정서진 도착 · 34.5km · 자전거 회수 용달비 ₩80,000 별도',
        price_modifier_krw: 0,
        flat_fee_krw: 80000,
        duration_hours: 5,
      },
    ],
    includes: [
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '여행자 보험',
    ],
    excludes: [
      '편도 이용 시 자전거 회수 용달비 (₩80,000, 1회 고정)',
      '전문 가이드 (선택 추가, +₩100,000 / 최대 10인)',
      '개인 식음료',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
    ],
    highlights: [
      '당산역 출발 → 서울식물원 (8km)',
      '서울식물원 → 아라항 (+6.5km)',
      '아라항 → 아라마루 전망대 (+9.5km)',
      '아라마루 전망대 → 정서진 서해 낙조 포인트 (+10.5km)',
      '왕복 69km / 편도 34.5km 선택 가능',
      '전기자전거 및 일반 고급 자전거 선택',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-06-05T00:00:00Z',
    updated_at: '2026-06-05T00:00:00Z',
  },

  // ── 활성 상품 ─────────────────────────────────────────────
  {
    id: '5',
    title: '행주산성 바이크투어',
    title_en: 'Haengju Fortress Bike Tour',
    slug: 'haengju-fortress-tour',
    description:
      '당산역에서 출발해 난지 하늘공원의 꽃밭과 메타세쿼이아 숲을 지나 행주산성까지 달리고, 아라항·서울식물원·선유도공원을 거쳐 한강라면으로 마무리하는 32km 순환 코스. 역사·자연·도시를 한 번에 즐기는 힐링 라이딩입니다.',
    short_description: '당산역 출발 · 난지하늘공원·행주산성·선유도 순환 · 32km · 한강라면 포함',
    category: 'cultural',
    difficulty: 'moderate',
    duration_hours: 6.5,
    distance_km: 32,
    max_participants: 50,
    price_krw: 50000,
    price_usd: 38,
    thumbnail_url: '/stop-haengju-fortress.png',
    images: [
      '/stop-ara-dangsan.png',
      '/stop-haengju-nanjido.png',
      '/stop-haengju-fortress.png',
      '/stop-ara-port.png',
      '/stop-ara-botanic.png',
      '/stop-haengju-seonyudo.png',
      '/stop-ramen.jpg',
    ],
    meeting_point: '당산역 2번 출구 (Dangsan Station, Exit 2)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    includes: [
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '여행자 보험',
      '한강라면 (선유도 포인트)',
    ],
    excludes: [
      '전문 가이드 (선택 추가, +₩100,000 / 최대 10인)',
      '개인 식음료',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      '당산역 출발 → 난지 하늘공원 (+5km) · 꽃밭 & 메타세쿼이아 숲',
      '난지 하늘공원 → 행주산성 (+6.5km) · 역사 유적지',
      '행주산성 → 아라항 현대아울렛 (+6km) · 수상레저',
      '아라항 → 서울식물원 (+6km) · 도심 속 열대 온실',
      '서울식물원 → 선유도공원 (+7km) · 한강 섬 공원',
      '한강라면 포함 (투어 가격에 포함!)',
      '선유도공원 → 당산역 귀환 (+1.5km) · 32km 완주',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-06-05T00:00:00Z',
    updated_at: '2026-06-05T00:00:00Z',
  },

  // ── 활성 상품 ─────────────────────────────────────────────
  {
    id: '6',
    title: '임진각 바이크투어',
    title_en: 'Imjingak Bike Tour',
    slug: 'imjingak-tour',
    description:
      '당산역에서 출발해 난지 하늘공원, 행주산성, 파주 출판단지, 통일전망대, 헤이리 예술마을을 지나 임진각까지 달리는 편도 75km 장거리 코스. 한강과 임진강을 따라 역사·예술·자연을 한 번에 만끽하는 특별한 라이딩입니다. 왕복(150km)과 편도(75km) 중 선택 가능합니다.',
    short_description: '당산역 출발 · 행주산성·출판단지·통일전망대·헤이리·임진각 · 왕복/편도 선택',
    category: 'cultural',
    difficulty: 'hard',
    duration_hours: 12,
    distance_km: 150,
    max_participants: 50,
    price_krw: 50000,
    price_usd: 38,
    thumbnail_url: '/stop-imjingak.png',
    images: [
      '/stop-ara-dangsan.png',
      '/stop-haengju-nanjido.png',
      '/stop-haengju-fortress.png',
      '/stop-imjingak-chulpandanji.png',
      '/stop-imjingak-tongiltower.png',
      '/stop-imjingak-heyri.png',
      '/stop-imjingak.png',
    ],
    meeting_point: '당산역 2번 출구 (Dangsan Station, Exit 2)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    options: [
      {
        id: 'roundtrip',
        label: '왕복',
        label_en: 'Round Trip',
        description: '당산역 출발 → 임진각 → 당산역 복귀 · 150km · 소요시간 10시간~15시간',
        price_modifier_krw: 0,
        duration_hours: 12,
      },
      {
        id: 'oneway',
        label: '편도',
        label_en: 'One Way',
        description: '당산역 출발 → 임진각 도착 · 75km · 소요시간 8시간~10시간 · 자전거 회수 용달비 ₩100,000 별도',
        price_modifier_krw: 0,
        flat_fee_krw: 100000,
        duration_hours: 9,
      },
    ],
    includes: [
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '여행자 보험',
    ],
    excludes: [
      '편도 이용 시 자전거 회수 용달비 (₩100,000, 1회 고정)',
      '전문 가이드 (선택 추가, +₩100,000 / 최대 10인)',
      '개인 식음료',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '장거리(75km~) 라이딩 경험 권장',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      '당산역 출발 → 난지 하늘공원 (+5km) · 꽃밭 & 전망',
      '난지 하늘공원 → 행주산성 (+7.7km) · 역사 유적지',
      '행주산성 → 파주 출판단지 (+20km) · 책과 문화의 거리',
      '출판단지 → 통일전망대 (+12km) · 임진강 & 북녘 조망',
      '통일전망대 → 헤이리 예술마을 (+1km) · 갤러리 & 카페',
      '헤이리 예술마을 → 임진각 (+25km) · 분단의 역사 현장',
      '왕복 150km / 편도 75km 선택 가능',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-06-07T00:00:00Z',
    updated_at: '2026-06-07T00:00:00Z',
  },

  // ── 오픈 예정 ─────────────────────────────────────────────
  {
    id: '2',
    title: '남해안 해안 라이딩',
    title_en: 'South Coast Cycling Tour',
    slug: 'south-coast-tour',
    description: '탁 트인 남해 바다를 따라 달리는 해안 투어. 곧 오픈됩니다.',
    short_description: '시원한 남해 해안선을 달리는 프리미엄 라이딩',
    category: 'coastal',
    difficulty: 'moderate',
    duration_hours: 5,
    distance_km: 30,
    max_participants: 20,
    price_krw: 79000,
    price_usd: 60,
    thumbnail_url: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=1200&q=80'],
    meeting_point: '추후 공개',
    includes: ['자전거', '헬멧', '가이드'],
    excludes: ['개인 식음료'],
    requirements: ['기본 자전거 탑승 가능자'],
    highlights: ['남해 해안 절경', '일몰 포인트'],
    rating: 0,
    review_count: 0,
    is_active: false,
    created_at: '2026-05-01T00:00:00Z',
    updated_at: '2026-05-30T00:00:00Z',
  },
  {
    id: '3',
    title: '제주 환상 자전거길',
    title_en: 'Jeju Island Cycling Tour',
    slug: 'jeju-cycling-tour',
    description: '제주 올레길과 해안도로를 달리는 프리미엄 투어. 곧 오픈됩니다.',
    short_description: '제주 해안도로와 오름을 달리는 힐링 라이딩',
    category: 'coastal',
    difficulty: 'easy',
    duration_hours: 6,
    distance_km: 40,
    max_participants: 15,
    price_krw: 129000,
    price_usd: 98,
    thumbnail_url: 'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=1200&q=80'],
    meeting_point: '추후 공개',
    includes: ['자전거', '헬멧', '가이드'],
    excludes: ['항공/숙박'],
    requirements: ['기본 자전거 탑승 가능자'],
    highlights: ['성산일출봉', '해안도로', '오름'],
    rating: 0,
    review_count: 0,
    is_active: false,
    created_at: '2026-05-01T00:00:00Z',
    updated_at: '2026-05-30T00:00:00Z',
  },
]

export const mockReviews: Review[] = []
