import type { Tour, Review } from '@/types'

export const mockTours: Tour[] = [
  // ── 활성 상품 ──────────────────────────────────────────────
  {
    id: '1',
    sort_order: 1,
    title: '한강 바이크투어',
    title_en: 'Han River Bike Tour',
    slug: 'hangang-healing-tour',
    description:
      '자전거 전문가들이 직접 달려보며 설계한 한강 힐링 코스. 당산역에서 출발해 샛강 생태공원을 지나, 반포대교 분수 포인트에서 감동을 느끼고, 한강라면으로 에너지 보충 후 여의도까지 달리는 프리미엄 순환 투어입니다. 일반 자전거 / MTB·로드 / 전기자전거 중 원하는 스타일로 선택하세요.',
    short_description: '당산역 출발 · 샛강·반포·여의도 순환 · 3~4시간 · 자전거 3종 선택',
    category: 'city',
    difficulty: 'easy',
    duration_hours: 3.5,
    distance_km: 21.2,
    max_participants: 50,
    price_krw: 50000,
    price_usd: 38,
    thumbnail_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
      'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=1200&q=80',
      'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=1200&q=80',
    ],
    meeting_point: '당산역 4번 출구 (Dangsan Station, Exit 4)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    includes: [
      '자전거 1대 (로드 / MTB / 전기자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '위치추적 장치',
      '도난 방지 알람',
      '한강라면 (반포대교 포인트)',
    ],
    excludes: [
      '전문 가이드 (선택 추가, +₩100,000 / 최대 10인)',
      '개인 여행자 보험 (별도 가입 권장)',
      '서울의 달 기구 탑승권 (현장 구매 가능)',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      '당산역 출발 → 샛강 생태공원 (도심 속 자연)',
      '한강대교 → 반포대교 분수 뷰포인트',
      '한강라면 포인트 (중간 휴식)',
      '노량대교 → 여의도 한강공원',
      '서울의 달 기구 탑승 가능 (현장 개별 구매)',
      '블랙박스로 녹화된 나만의 투어 영상 제공',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-05-01T00:00:00Z',
    updated_at: '2026-05-30T00:00:00Z',
  },

  // ── 활성 상품 ─────────────────────────────────────────────
  {
    id: '4',
    sort_order: 2,
    title: '한강 아라뱃길 바이크투어',
    title_en: 'Han River Ara Waterway Bike Tour',
    slug: 'ara-waterway-tour',
    description:
      '당산역에서 출발해 서울식물원, 경인아라뱃길을 따라 아라마루 전망대, 정서진(서해)까지 달리는 장거리 코스. 도심 한강에서 서해까지 이어지는 특별한 라이딩 경험. 왕복(34.5km)과 편도(34.5km, 용달비 별도) 중 선택 가능합니다.',
    short_description: '당산역 출발 · 서울식물원·아라뱃길·정서진(서해) · 왕복/편도 선택',
    category: 'city',
    difficulty: 'moderate',
    duration_hours: 7,
    distance_km: 69,
    max_participants: 50,
    price_krw: 70000,
    price_usd: 53,
    thumbnail_url: '/stop-ara-waterfall.png',
    images: [
      '/stop-ara-dangsan.png',
      '/stop-ara-botanic.png',
      '/stop-ara-port.png',
      '/stop-ara-tower.png',
      '/stop-ara-waterfall.png',
      '/stop-ara-bikeway.png',
      '/stop-ara-jeongseojin.png',
      '/stop-jeongseojin.png',
    ],
    meeting_point: '당산역 4번 출구 (Dangsan Station, Exit 4)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    options: [
      {
        id: 'roundtrip',
        label: '왕복',
        label_en: 'Round Trip',
        description: '당산역 출발 → 정서진 → 당산역 복귀 · 69km',
        price_modifier_krw: 0,
        duration_hours: 7,
      },
      {
        id: 'oneway',
        label: '편도',
        label_en: 'One Way',
        description: '당산역 출발 → 정서진 도착 · 34.5km · 자전거 회수 용달비 ₩80,000 별도',
        price_modifier_krw: 0,
        flat_fee_krw: 80000,
        duration_hours: 5,
      },
    ],
    includes: [
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '운영자 배상책임보험 가입',
    ],
    excludes: [
      '편도 이용 시 자전거 회수 용달비 (₩80,000, 1회 고정)',
      '전문 가이드 (선택 추가, +₩100,000 / 최대 10인)',
      '개인 식음료',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
    ],
    highlights: [
      '당산역 출발 → 서울식물원 (8km)',
      '서울식물원 → 아라항 (+6.5km)',
      '아라항 → 아라마루 전망대 (+9.5km)',
      '아라마루 전망대 → 정서진 서해 낙조 포인트 (+10.5km)',
      '왕복 69km / 편도 34.5km 선택 가능',
      '전기자전거 및 일반 고급 자전거 선택',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-06-05T00:00:00Z',
    updated_at: '2026-06-05T00:00:00Z',
  },

  // ── 활성 상품 ─────────────────────────────────────────────
  {
    id: '5',
    sort_order: 3,
    title: '행주산성 바이크투어',
    title_en: 'Haengju Fortress Bike Tour',
    slug: 'haengju-fortress-tour',
    description:
      '당산역에서 출발해 난지 하늘공원의 꽃밭과 메타세쿼이아 숲을 지나 행주산성까지 달리고, 아라항·서울식물원·선유도공원을 거쳐 한강라면으로 마무리하는 32km 순환 코스. 역사·자연·도시를 한 번에 즐기는 힐링 라이딩입니다.',
    short_description: '당산역 출발 · 난지하늘공원·행주산성·선유도 순환 · 32km · 한강라면 포함',
    category: 'cultural',
    difficulty: 'moderate',
    duration_hours: 6.5,
    distance_km: 32,
    max_participants: 50,
    price_krw: 50000,
    price_usd: 38,
    thumbnail_url: '/stop-haengju-fortress.png',
    images: [
      '/stop-ara-dangsan.png',
      '/stop-haengju-nanjido.png',
      '/stop-haengju-fortress.png',
      '/stop-ara-port.png',
      '/stop-ara-botanic.png',
      '/stop-haengju-seonyudo.png',
      '/stop-ramen.jpg',
    ],
    meeting_point: '당산역 4번 출구 (Dangsan Station, Exit 4)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    includes: [
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '운영자 배상책임보험 가입',
      '한강라면 (선유도 포인트)',
    ],
    excludes: [
      '전문 가이드 (선택 추가, +₩100,000 / 최대 10인)',
      '개인 식음료',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      '당산역 출발 → 난지 하늘공원 (+5km) · 꽃밭 & 메타세쿼이아 숲',
      '난지 하늘공원 → 행주산성 (+6.5km) · 역사 유적지',
      '행주산성 → 아라항 현대아울렛 (+6km) · 수상레저',
      '아라항 → 서울식물원 (+6km) · 도심 속 열대 온실',
      '서울식물원 → 선유도공원 (+7km) · 한강 섬 공원',
      '한강라면 포함 (투어 가격에 포함!)',
      '선유도공원 → 당산역 귀환 (+1.5km) · 32km 완주',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-06-05T00:00:00Z',
    updated_at: '2026-06-05T00:00:00Z',
  },

  // ── 활성 상품 ─────────────────────────────────────────────
  {
    id: '6',
    sort_order: 4,
    title: '임진각 바이크투어',
    title_en: 'Imjingak Bike Tour',
    slug: 'imjingak-tour',
    description:
      '당산역에서 출발해 난지 하늘공원, 행주산성, 파주 출판단지, 통일전망대, 헤이리 예술마을을 지나 임진각까지 달리는 편도 75km 장거리 코스. 한강과 임진강을 따라 역사·예술·자연을 한 번에 만끽하는 특별한 라이딩입니다. 왕복(150km)과 편도(75km) 중 선택 가능합니다.',
    short_description: '당산역 출발 · 행주산성·출판단지·통일전망대·헤이리·임진각 · 왕복/편도 선택',
    category: 'cultural',
    difficulty: 'hard',
    duration_hours: 12,
    distance_km: 150,
    max_participants: 50,
    price_krw: 50000,
    price_usd: 38,
    thumbnail_url: '/stop-imjingak.png',
    images: [
      '/stop-ara-dangsan.png',
      '/stop-haengju-nanjido.png',
      '/stop-haengju-fortress.png',
      '/stop-imjingak-chulpandanji.png',
      '/stop-imjingak-tongiltower.png',
      '/stop-imjingak-heyri.png',
      '/stop-imjingak.png',
    ],
    meeting_point: '당산역 4번 출구 (Dangsan Station, Exit 4)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    options: [
      {
        id: 'roundtrip',
        label: '왕복',
        label_en: 'Round Trip',
        description: '당산역 출발 → 임진각 → 당산역 복귀 · 150km · 소요시간 10시간~15시간',
        price_modifier_krw: 0,
        duration_hours: 12,
      },
      {
        id: 'oneway',
        label: '편도',
        label_en: 'One Way',
        description: '당산역 출발 → 임진각 도착 · 75km · 소요시간 8시간~10시간 · 자전거 회수 용달비 ₩100,000 별도',
        price_modifier_krw: 0,
        flat_fee_krw: 100000,
        duration_hours: 9,
      },
    ],
    includes: [
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '운영자 배상책임보험 가입',
    ],
    excludes: [
      '편도 이용 시 자전거 회수 용달비 (₩100,000, 1회 고정)',
      '전문 가이드 (선택 추가, +₩100,000 / 최대 10인)',
      '개인 식음료',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '장거리(75km~) 라이딩 경험 권장',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      '당산역 출발 → 난지 하늘공원 (+5km) · 꽃밭 & 전망',
      '난지 하늘공원 → 행주산성 (+7.7km) · 역사 유적지',
      '행주산성 → 파주 출판단지 (+20km) · 책과 문화의 거리',
      '출판단지 → 통일전망대 (+12km) · 임진강 & 북녘 조망',
      '통일전망대 → 헤이리 예술마을 (+1km) · 갤러리 & 카페',
      '헤이리 예술마을 → 임진각 (+25km) · 분단의 역사 현장',
      '왕복 150km / 편도 75km 선택 가능',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-06-07T00:00:00Z',
    updated_at: '2026-06-07T00:00:00Z',
  },

  // ── 활성 상품 ─────────────────────────────────────────────
  {
    id: '7',
    sort_order: 5,
    title: '평화누리 자전거 1길',
    title_en: 'Gimpo Peace Nuri Cycling Route 1',
    slug: 'peace-nuri-1',
    description:
      '김포 전류리포구에서 출발해 DMZ 철책선 옆 평화의 자전거길을 따라 달리는 역사·자연 테마 코스. 석탄리 철새 도래지, 애기봉 전망대에서 북녘 땅을 바라보고, 김포 DMZ평화의길 거점센터, 덕포진 교육박물관을 거쳐 대명항 활어 시장까지 이어지는 편도 43km 투어입니다. 철책선 옆 자전거길이 주는 독특한 감동과 서해 항구의 신선한 공기가 어우러진 특별한 하루.',
    short_description: '전류리포구 출발 · 철책선 평화의길 · 애기봉 전망대 · 대명항 · 편도 43km',
    category: 'cultural',
    difficulty: 'moderate',
    duration_hours: 6.5,
    distance_km: 43,
    max_participants: 50,
    price_krw: 88000,
    price_usd: 65,
    thumbnail_url: '/stop-peacenuri-thumbnail.png',
    images: [
      '/stop-peacenuri-thumbnail.png',
      '/stop-peacenuri-jeonryuri.png',
      '/stop-peacenuri-seoktanri.png',
      '/stop-peacenuri-dmz.png',
      '/stop-peacenuri-kimpouni.png',
      '/stop-peacenuri-seokjeong.png',
      '/stop-peacenuri-deokpojin.png',
      '/stop-peacenuri-daemyeong.png',
    ],
    meeting_point: '전류리포구 (김포시 통진읍)',
    meeting_point_lat: 37.7063,
    meeting_point_lng: 126.6562,
    includes: [
      '전문 가이드 1명',
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '잠금장치 제공',
      '운영자 배상책임보험 가입',
      '중식 1식 + 음료 제공',
    ],
    excludes: [
      '개인 간식·추가 식음료',
      '애기봉 전망대 입장료 (현장 개별 결제)',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '5인 이상 출발 (최소 인원 미충족 시 일정 변경 안내)',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      '전류리포구 출발 → 석탄리 철새 도래지 (+4km) · 철책선 옆 평화의 자전거길',
      '석탄리 철새 도래지 → 애기봉 전망대 (+7.2km) · 북한이 보이는 최전방 전망대',
      '애기봉 전망대 → 김포 DMZ평화의길 거점센터 (+4km) · DMZ 테마 전시',
      '거점센터 → 김포대학 (+10km) · 한적한 시골길 라이딩',
      '김포대학 → 석정초등학교 (+4.5km) · 우주 테마 벽화 포토스팟',
      '석정초등학교 → 덕포진 교육박물관 (+4.5km) · 조선시대 역사 현장',
      '덕포진 교육박물관 → 대명항 (+1.5km) · 서해 신선 수산시장 마무리',
      '중식 1식 + 음료 투어 가격에 포함',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-06-18T00:00:00Z',
    updated_at: '2026-06-18T00:00:00Z',
  },

  // ── 활성 상품 ─────────────────────────────────────────────
  {
    id: '8',
    sort_order: 6,
    title: '호반 춘천코스 바이크투어',
    title_en: 'Lakeside Chuncheon Bike Tour',
    slug: 'chuncheon-lakeside-tour',
    description:
      '당산역에서 출발해 한강을 따라 팔당, 두물머리, 세미원을 지나 북한강 자전거길을 달려 자라섬, 남이섬, 강촌유원지, 춘천호수케블카, 레고랜드까지 이어지는 편도 129km 대장정. 두 강이 만나는 두물머리의 절경과 연꽃 가득한 세미원, 아름다운 북한강변을 하루에 모두 경험하는 프리미엄 투어입니다. 춘천역에서 차량으로 용산역까지 복귀하여 편하게 마무리합니다.',
    short_description: '당산역 출발 · 팔당·두물머리·자라섬·남이섬·강촌·춘천 · 편도 129km · 차량 복귀',
    category: 'cultural',
    difficulty: 'hard',
    duration_hours: 13,
    distance_km: 129,
    max_participants: 50,
    price_krw: 150000,
    price_usd: 113,
    thumbnail_url: '/stop-chuncheon-jaraseom.png',
    images: [
      '/stop-chuncheon-dangsan.png',
      '/stop-chuncheon-yeouido.png',
      '/stop-chuncheon-banpo.png',
      '/stop-chuncheon-paldang.png',
      '/stop-chuncheon-semiwon.png',
      '/stop-chuncheon-dumulmeori.png',
      '/stop-chuncheon-lotus.png',
      '/stop-chuncheon-jaraseom.png',
      '/stop-chuncheon-namisum.png',
      '/stop-chuncheon-legoland.png',
      '/stop-chuncheon-bridge.png',
    ],
    meeting_point: '당산역 4번 출구 (Dangsan Station, Exit 4)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    includes: [
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '운영자 배상책임보험 가입',
      '춘천역 → 용산역 차량 복귀 서비스',
    ],
    excludes: [
      '전문 가이드 (선택 추가, +₩100,000 / 최대 10인)',
      '개인 식음료',
      '팔당 초계국수 (현장 개별 결제)',
      '남이섬 입장료 (현장 개별 결제)',
      '춘천호수케블카 이용료 (현장 개별 결제)',
      '레고랜드 입장료 (현장 개별 결제)',
    ],
    requirements: [
      '장거리(100km 이상) 라이딩 경험 권장',
      '기본적인 자전거 탑승이 가능한 분',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      '당산역 출발 → 잠실 (+20km) · 한강 자전거도로',
      '잠실 → 팔당 초계국수 (+21km) · 팔당대교 뷰포인트',
      '팔당 → 두물머리·세미원 (+10km) · 두 강이 만나는 비경·연꽃정원',
      '두물머리 → 물의정원 (+3km) · 수생식물 생태공원',
      '물의정원 → 자라섬 (+40km) · 북한강 자전거길 하이라이트',
      '자라섬 → 남이섬 (+3km) · 사계절 아름다운 섬 라이딩',
      '남이섬 → 강촌유원지 (+16km) · 강촌 계곡',
      '강촌유원지 → 춘천호수케블카 (+10km) · 의암호 위를 나는 케이블카',
      '춘천호수케블카 → 레고랜드 (+6km) · 레고랜드 코리아',
      '레고랜드 → 춘천역(차량) → 용산역(차량) · 편안한 서울 복귀',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-06-26T00:00:00Z',
    updated_at: '2026-06-26T00:00:00Z',
  },

  // ── 활성 상품 ─────────────────────────────────────────────
  {
    id: '10',
    sort_order: 7,
    title: '올림픽공원 바이크투어',
    title_en: 'Olympic Park Bike Tour',
    slug: 'olympic-park-tour',
    description:
      '당산역에서 출발해 여의도 한강공원, 반포대교 분수 뷰포인트, 잠실운동장을 지나 올림픽공원까지 달리는 한강 동쪽 순환 코스. 서울의 대표 랜드마크를 자전거로 한 번에 연결하는 도심 힐링 투어입니다. 왕복(54km)과 편도(27km) 중 선택 가능하며, 한강라면과 음료가 포함됩니다.',
    short_description: '당산역 출발 · 여의도·반포대교·잠실·올림픽공원 · 왕복/편도 선택 · 가이드 포함',
    category: 'city',
    difficulty: 'moderate',
    duration_hours: 6.5,
    distance_km: 54,
    max_participants: 50,
    price_krw: 88000,
    price_usd: 65,
    thumbnail_url: '/stop-olympic-park.png',
    images: [
      '/stop-ara-dangsan.png',
      '/stop-olympic-yeouido.png',
      '/stop-olympic-banpo.png',
      '/stop-olympic-jamsil.png',
      '/stop-olympic-park.png',
    ],
    meeting_point: '당산역 4번 출구 (Dangsan Station, Exit 4)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    options: [
      {
        id: 'roundtrip',
        label: '왕복',
        label_en: 'Round Trip',
        description: '당산역 출발 → 올림픽공원 → 당산역 복귀 · 54km · 소요 6~8시간',
        price_modifier_krw: 0,
        duration_hours: 7,
      },
      {
        id: 'oneway',
        label: '편도',
        label_en: 'One Way',
        description: '당산역 출발 → 올림픽공원 도착 · 27km · 소요 5~6시간 · 자전거 회수 용달비 ₩80,000 별도',
        price_modifier_krw: 0,
        flat_fee_krw: 80000,
        duration_hours: 5.5,
      },
    ],
    includes: [
      '전문 가이드 1명',
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프·잠금장치 제공',
      '운영자 배상책임보험 가입',
      '한강라면 (반포대교 포인트)',
      '음료 제공',
    ],
    excludes: [
      '편도 이용 시 자전거 회수 용달비 (₩80,000, 1회 고정)',
      '개인 추가 식음료',
      '올림픽공원 입장료 (무료 구간 라이딩)',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '5명 이상 출발 (최소 인원 미충족 시 일정 조율)',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      '당산역 출발 → 여의도 한강공원 (+3km) · 한강버스 뷰포인트',
      '여의도 → 반포대교 (+7.5km) · 세빛섬·분수 야경 포인트',
      '반포대교 → 잠실운동장 (+9km) · 서울 동부 한강변 라이딩',
      '잠실운동장 → 올림픽공원 (+7.5km) · 공원 내 자전거도로 이용',
      '한강라면 포함 (반포대교 뷰포인트)',
      '왕복 54km / 편도 27km 선택 가능',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-06-26T00:00:00Z',
    updated_at: '2026-06-26T00:00:00Z',
  },

  // ── 활성 상품 (국토종주) ────────────────────────────────────
  {
    id: '9',
    sort_order: 8,
    title: '국토종주 바이크투어',
    title_en: 'Korea National Cycling Route',
    slug: 'national-cycling-route',
    description:
      '대한민국 자전거 여행의 최고봉, 한강·낙동강 국토종주 자전거길 전 구간(562km)을 완주하는 5박6일 올인클루시브 투어. 인천 아라서해갑문을 출발해 한강을 따라 달리고, 이화령을 넘어 낙동강을 따라 부산 낙동강하구뚝까지 완주합니다. 전문 가이드와 화물차가 함께하며 자전거·숙소·1일3식(바베큐 2회·음료 무한)을 모두 포함합니다. 국토교통부·행정안전부 공인 국토종주 완주 인증에 도전하세요.',
    short_description: '아라서해갑문 출발 · 이화령 고개 · 낙동강하구뚝 도착 · 562km · 5박6일 · 1인 990,000원',
    category: 'national',
    difficulty: 'hard',
    duration_hours: 144,
    distance_km: 562,
    max_participants: 30,
    price_krw: 990000,
    price_usd: 745,
    thumbnail_url: '/stop-national-ihwaryeong.png',
    images: [
      '/stop-national-ara-west.png',
      '/stop-national-ara-hangang.png',
      '/stop-national-yeouido.png',
      '/stop-national-ttukseom.png',
      '/stop-national-gwangnaru.png',
      '/stop-national-neungnae.png',
      '/stop-national-yangpyeong.png',
      '/stop-national-ipo.png',
      '/stop-national-yeoju.png',
      '/stop-national-gangcheon.png',
      '/stop-national-binae.png',
      '/stop-national-tangeum.png',
      '/stop-national-suanbo.png',
      '/stop-national-ihwaryeong.png',
      '/stop-national-mungyeong.png',
      '/stop-national-sangju-bridge.png',
      '/stop-national-sangju.png',
      '/stop-national-nakdan.png',
      '/stop-national-gumi.png',
      '/stop-national-chilgok.png',
      '/stop-national-goryeong.png',
      '/stop-national-dalseong.png',
      '/stop-national-changnyeong.png',
      '/stop-national-haman.png',
      '/stop-national-yangsan.png',
      '/stop-national-nakdong-end.png',
    ],
    meeting_point: '아라 서해갑문 (인천광역시 서구 오류동)',
    meeting_point_lat: 37.5765,
    meeting_point_lng: 126.5935,
    includes: [
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '국토종주 패스포트 제공',
      '운영자 배상책임보험 가입',
      '전문 가이드 1명 (전 구간 동행)',
      '화물차 제공 (부산→서울 자전거 회수)',
      '블랙박스 장착 + 완주 영상 편집 제공',
      '펌프·비상 공구·비상 의약품',
      '숙박 5박 (2인1실 & 단체룸 / 모텔·캠핑장·팬션)',
      '식사 1일3식 (석식 2회 바베큐 · 음료 무한)',
      '완주 후 영상편집 제공',
    ],
    excludes: [
      '인천 집결 교통비 (아라서해갑문 이동)',
      '부산 귀가 교통비 (낙동강하구뚝 → 개인 귀가)',
      '개인 간식',
    ],
    requirements: [
      '장거리(100km 이상) 라이딩 경험 필수',
      '10명 이상 출발 (최소 인원 미충족 시 일정 조율)',
      '5박6일 일정 참여 가능한 분',
      '만 15세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      'Day 1 · 아라서해갑문 → 뚝섬 (51km) · 한강 도심 라이딩',
      'Day 2 · 뚝섬 → 양평미술관 (75km) · 남한강 자전거길 진입',
      'Day 3 · 양평 → 탄금대 (103km) · 이포보·여주보·비내섬 통과',
      'Day 4 · 탄금대 → 상주 (106km) · 수안보·이화령 고개 하이라이트',
      'Day 5 · 상주 → 달성보 (127km) · 낙동강 상류 보 연속 라이딩',
      'Day 6 · 달성보 → 낙동강하구뚝 (100km) · 완주 인증 도전!',
      '국토교통부·행정안전부 공인 국토종주 완주 인증 취득',
      '화물차 동행으로 짐 걱정 없이 달리는 완전 지원 패키지',
      '석식 2회 바베큐 & 음료 무한 제공',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-06-26T00:00:00Z',
    updated_at: '2026-06-26T00:00:00Z',
  },

  // ── 활성 상품 ─────────────────────────────────────────────
  {
    id: '11',
    sort_order: 9,
    title: '양수리 바이크투어',
    title_en: 'Yangsu Han River & Dumulmeori Bike Tour',
    slug: 'yangsu-tour',
    description:
      '당산역에서 출발해 샛강 생태공원, 반포대교, 잠실을 지나 미사리 조정경기장, 팔당댐, 두물머리·세미원까지 달리는 편도 51km / 왕복 102km 1일 코스. 남한강과 북한강이 만나는 두물머리의 장엄한 풍경과 세미원의 연꽃정원을 하루에 만끽하는 올인클루시브 투어. 전문 가이드, 식사 2끼, 음료, 세미원 입장료까지 모두 포함됩니다.',
    short_description: '당산역 출발 · 미사리·팔당댐·두물머리·세미원 · 편도 51km/왕복 102km · 식사2·세미원입장 포함',
    category: 'cultural',
    difficulty: 'hard',
    duration_hours: 10,
    distance_km: 102,
    max_participants: 50,
    price_krw: 105000,
    price_usd: 80,
    thumbnail_url: '/stop-chuncheon-dumulmeori.png',
    images: [
      '/stop-ara-dangsan.png',
      '/stop-chuncheon-banpo.png',
      '/stop-yangsu-jamsil-night.png',
      '/stop-yangsu-misari.png',
      '/stop-yangsu-paldang.png',
      '/stop-chuncheon-semiwon.png',
      '/stop-yangsu-semiwon-bridge.png',
      '/stop-chuncheon-lotus.png',
      '/stop-chuncheon-dumulmeori.png',
      '/stop-yangsu-dumulmeori-dawn.png',
    ],
    meeting_point: '당산역 4번 출구 (Dangsan Station, Exit 4)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    options: [
      {
        id: 'roundtrip',
        label: '왕복',
        label_en: 'Round Trip',
        description: '당산역 출발 → 두물머리·세미원 → 당산역 복귀 · 102km',
        price_modifier_krw: 0,
        duration_hours: 10,
      },
      {
        id: 'oneway',
        label: '편도',
        label_en: 'One Way',
        description: '당산역 출발 → 두물머리·세미원 도착 · 51km · 자전거 회수 용달비 ₩100,000 별도',
        price_modifier_krw: 0,
        flat_fee_krw: 100000,
        duration_hours: 6,
      },
    ],
    includes: [
      '전문 가이드 1명',
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '운영자 배상책임보험 가입',
      '식사 2끼 (점심 + 저녁)',
      '음료 제공',
      '세미원 공원 입장료',
    ],
    excludes: [
      '편도 이용 시 자전거 회수 용달비 (₩100,000, 1회 고정)',
      '개인 간식·추가 식음료',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '8인 이상 출발 (최소 인원 미충족 시 일정 조율)',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      '당산역 출발 → 샛강 생태공원 (+2km) · 도심 속 생태 하천',
      '샛강 → 반포대교 (+7.5km) · 세빛섬·분수 야경 뷰포인트',
      '반포대교 → 잠실 (+9.5km) · 잠실대교 야경 포인트',
      '잠실 → 미사리 조정경기장 (+16km) · 수상레포츠 명소',
      '미사리 → 팔당댐 (+4km) · 팔당호 절경과 산악 뷰',
      '팔당댐 → 두물머리·세미원 (+12km) · 두 강이 만나는 비경·연꽃정원',
      '왕복 102km / 편도 51km 선택 가능',
      '식사 2끼 + 음료 + 세미원 입장료 포함',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-07-09T00:00:00Z',
    updated_at: '2026-07-09T00:00:00Z',
  },

  // ── 활성 상품 ─────────────────────────────────────────────
  {
    id: '14',
    sort_order: 10,
    title: '보라매공원 바이크투어',
    title_en: 'Boramae Park Bike Tour',
    slug: 'boramae-park-tour',
    description:
      '당산역에서 출발해 안양천 합수부를 따라 양천 양궁장에서 특별한 양궁 체험을 즐기고, 장미꽃 가득한 도림천 산책로를 지나 서울 서남권 최대 공원인 보라매공원까지 달리는 감성 순환 코스. 전문 가이드, 식사 1식, 한강라면, 음료, 양궁 체험이 모두 포함된 특별 투어입니다.',
    short_description: '당산역 출발 · 안양합수부·양천양궁장·도림천·보라매공원 순환 · 5~7시간 · 양궁체험 포함',
    category: 'city',
    difficulty: 'easy',
    duration_hours: 6,
    distance_km: 34,
    max_participants: 50,
    price_krw: 93000,
    price_usd: 70,
    thumbnail_url: '/stop-boramae-park-night.png',
    images: [
      '/stop-ara-dangsan.png',
      '/stop-boramae-anyang.png',
      '/stop-boramae-archery.png',
      '/stop-boramae-dorimcheon.png',
      '/stop-boramae-park-night.png',
      '/stop-boramae-park.png',
    ],
    meeting_point: '당산역 4번 출구 (Dangsan Station, Exit 4)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    options: [
      {
        id: 'roundtrip',
        label: '왕복',
        label_en: 'Round Trip',
        description: '당산역 출발 → 보라매공원 → 도림천 → 당산역 복귀 · 약 34km · 소요 6~7시간',
        price_modifier_krw: 0,
        duration_hours: 6,
      },
      {
        id: 'oneway',
        label: '편도',
        label_en: 'One Way',
        description: '당산역 출발 → 보라매공원 도착 · 약 17km · 소요 5시간 · 자전거 회수 용달비 ₩80,000 별도',
        price_modifier_krw: 0,
        flat_fee_krw: 80000,
        duration_hours: 5,
      },
    ],
    includes: [
      '전문 가이드 1명',
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '운영자 배상책임보험 가입',
      '식사 1식 (점심)',
      '한강라면 (한강 포인트)',
      '음료 제공',
      '양천 양궁장 양궁 체험',
    ],
    excludes: [
      '편도 이용 시 자전거 회수 용달비 (₩80,000, 1회 고정)',
      '개인 간식·추가 식음료',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '8인 이상 출발 (최소 인원 미충족 시 일정 조율)',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      '당산역 출발 → 안양합수부 · 한강 자전거도로 시작점',
      '안양합수부 → 양천 양궁장 · 전문 양궁 체험 (포함!)',
      '양천 양궁장 → 도림천 산책로 · 장미꽃 가득한 도심 하천',
      '도림천 → 보라매공원 · 야경 분수·산책로 힐링',
      '왕복 34km / 편도 17km 선택 가능',
      '양궁 체험 + 식사 1식 + 한강라면 + 음료 포함',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-07-10T00:00:00Z',
    updated_at: '2026-07-10T00:00:00Z',
  },

  // ── 활성 상품 ─────────────────────────────────────────────
  {
    id: '13',
    sort_order: 11,
    title: '청계천 바이크투어',
    title_en: 'Cheonggyecheon Stream Bike Tour',
    slug: 'cheonggyecheon-tour',
    description:
      '당산역에서 출발해 여의도 한강공원을 지나 서울 도심 속 청계천을 달리는 감성 코스. 살곶이공원 물놀이장, 역사가 살아있는 용두공원, 그리고 서울의 상징 청계천 산책로까지 도시의 다채로운 매력을 자전거로 한 번에 경험합니다. 전문 가이드, 식사 1식, 한강라면, 음료가 모두 포함됩니다.',
    short_description: '당산역 출발 · 여의도·청계천·용두공원·살곶이공원 · 5~8시간 · 가이드·식사 포함',
    category: 'cultural',
    difficulty: 'moderate',
    duration_hours: 6,
    distance_km: 40,
    max_participants: 50,
    price_krw: 93000,
    price_usd: 70,
    thumbnail_url: '/stop-cheonggyecheon-stream.png',
    images: [
      '/stop-ara-dangsan.png',
      '/stop-seoulforest-ferry.png',
      '/stop-cheonggyecheon-stream.png',
      '/stop-cheonggyecheon-yongdu.png',
      '/stop-cheonggyecheon-salgoji.png',
    ],
    meeting_point: '당산역 4번 출구 (Dangsan Station, Exit 4)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    options: [
      {
        id: 'roundtrip',
        label: '왕복',
        label_en: 'Round Trip',
        description: '당산역 출발 → 청계천·살곶이 → 당산역 복귀 · 약 40km · 소요 6~8시간',
        price_modifier_krw: 0,
        duration_hours: 7,
      },
      {
        id: 'oneway',
        label: '편도',
        label_en: 'One Way',
        description: '당산역 출발 → 살곶이공원 도착 · 약 20km · 소요 5~6시간 · 자전거 회수 용달비 ₩80,000 별도',
        price_modifier_krw: 0,
        flat_fee_krw: 80000,
        duration_hours: 5,
      },
    ],
    includes: [
      '전문 가이드 1명',
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '운영자 배상책임보험 가입',
      '식사 1식 (점심)',
      '한강라면 (한강 포인트)',
      '음료 제공',
    ],
    excludes: [
      '편도 이용 시 자전거 회수 용달비 (₩80,000, 1회 고정)',
      '개인 간식·추가 식음료',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '8인 이상 출발 (최소 인원 미충족 시 일정 조율)',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      '당산역 출발 → 여의도 한강공원 · 한강버스 뷰포인트',
      '여의도 → 청계광장 · 서울 도심 속 물길 시작점',
      '청계천 산책로 · 빌딩 숲 사이 청량한 도심 하천',
      '용두공원 · 용 석상 분수와 역사 테마 공원',
      '살곶이공원 · 한강 합류 지점·여름 물놀이장',
      '왕복 40km / 편도 20km 선택 가능',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-07-10T00:00:00Z',
    updated_at: '2026-07-10T00:00:00Z',
  },

  // ── 활성 상품 ─────────────────────────────────────────────
  {
    id: '12',
    sort_order: 11,
    title: '서울숲 바이크투어',
    title_en: 'Seoul Forest Bike Tour',
    slug: 'seoul-forest-tour',
    description:
      '당산역에서 출발해 샛강 생태공원, 반포대교를 지나 도심 속 힐링 공간인 서울숲까지 달리고, 여의도 한강공원을 거쳐 당산역으로 돌아오는 왕복 34km 순환 코스. 전문 가이드, 식사 1식, 한강라면, 음료가 모두 포함된 알찬 반일~하루 투어입니다. 전기자전거 및 일반 고급 자전거 중 선택 가능.',
    short_description: '당산역 출발 · 샛강·반포대교·서울숲·여의도 순환 · 왕복 34km · 가이드·식사 포함',
    category: 'city',
    difficulty: 'easy',
    duration_hours: 6,
    distance_km: 34,
    max_participants: 50,
    price_krw: 93000,
    price_usd: 70,
    thumbnail_url: '/stop-seoulforest-park.png',
    images: [
      '/stop-ara-dangsan.png',
      '/stop-chuncheon-banpo.png',
      '/stop-seoulforest-park.png',
      '/stop-seoulforest-ferry.png',
    ],
    meeting_point: '당산역 4번 출구 (Dangsan Station, Exit 4)',
    meeting_point_lat: 37.5340,
    meeting_point_lng: 126.9012,
    options: [
      {
        id: 'roundtrip',
        label: '왕복',
        label_en: 'Round Trip',
        description: '당산역 출발 → 서울숲 → 여의도 → 당산역 복귀 · 34km · 소요 6~7시간',
        price_modifier_krw: 0,
        duration_hours: 6,
      },
      {
        id: 'oneway',
        label: '편도',
        label_en: 'One Way',
        description: '당산역 출발 → 서울숲 도착 · 17km · 소요 4~5시간 · 자전거 회수 용달비 ₩80,000 별도',
        price_modifier_krw: 0,
        flat_fee_krw: 80000,
        duration_hours: 5,
      },
    ],
    includes: [
      '전문 가이드 1명',
      '자전거 1대 (전기자전거 / 일반 고급 자전거 중 선택)',
      '헬멧 제공',
      '폰거치대 제공',
      '블랙박스 장착 + 투어 영상 제공',
      '펌프 제공',
      '운영자 배상책임보험 가입',
      '식사 1식 (점심)',
      '한강라면 (반포대교 포인트)',
      '음료 제공',
    ],
    excludes: [
      '편도 이용 시 자전거 회수 용달비 (₩80,000, 1회 고정)',
      '개인 간식·추가 식음료',
    ],
    requirements: [
      '기본적인 자전거 탑승이 가능한 분',
      '8인 이상 출발 (최소 인원 미충족 시 일정 조율)',
      '만 12세 이상 (미성년자는 보호자 동반)',
      '음주 상태 탑승 불가',
      '심장 질환, 임산부 등 격렬한 신체활동 제한자 참가 제한',
    ],
    highlights: [
      '당산역 출발 → 샛강 생태공원 (+2km) · 도심 속 생태 하천',
      '샛강 → 반포대교 (+7.5km) · 세빛섬·분수 야경 뷰포인트',
      '반포대교 → 서울숲 (+7.5km) · 사계절 아름다운 도심 숲',
      '서울숲 → 여의도 한강공원 (복귀) · 한강버스 뷰포인트',
      '한강라면 포함 (반포대교 포인트)',
      '왕복 34km / 편도 17km 선택 가능',
    ],
    rating: 0,
    review_count: 0,
    is_active: true,
    created_at: '2026-07-10T00:00:00Z',
    updated_at: '2026-07-10T00:00:00Z',
  },

  // ── 오픈 예정 ─────────────────────────────────────────────
  {
    id: '2',
    title: '남해안 해안 라이딩',
    title_en: 'South Coast Cycling Tour',
    slug: 'south-coast-tour',
    description: '탁 트인 남해 바다를 따라 달리는 해안 투어. 곧 오픈됩니다.',
    short_description: '시원한 남해 해안선을 달리는 프리미엄 라이딩',
    category: 'coastal',
    difficulty: 'moderate',
    duration_hours: 5,
    distance_km: 30,
    max_participants: 20,
    price_krw: 79000,
    price_usd: 60,
    thumbnail_url: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=1200&q=80'],
    meeting_point: '추후 공개',
    includes: ['자전거', '헬멧', '가이드'],
    excludes: ['개인 식음료'],
    requirements: ['기본 자전거 탑승 가능자'],
    highlights: ['남해 해안 절경', '일몰 포인트'],
    rating: 0,
    review_count: 0,
    is_active: false,
    created_at: '2026-05-01T00:00:00Z',
    updated_at: '2026-05-30T00:00:00Z',
  },
  {
    id: '3',
    title: '제주 환상 자전거길',
    title_en: 'Jeju Island Cycling Tour',
    slug: 'jeju-cycling-tour',
    description: '제주 올레길과 해안도로를 달리는 프리미엄 투어. 곧 오픈됩니다.',
    short_description: '제주 해안도로와 오름을 달리는 힐링 라이딩',
    category: 'coastal',
    difficulty: 'easy',
    duration_hours: 6,
    distance_km: 40,
    max_participants: 15,
    price_krw: 129000,
    price_usd: 98,
    thumbnail_url: 'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=1200&q=80'],
    meeting_point: '추후 공개',
    includes: ['자전거', '헬멧', '가이드'],
    excludes: ['항공/숙박'],
    requirements: ['기본 자전거 탑승 가능자'],
    highlights: ['성산일출봉', '해안도로', '오름'],
    rating: 0,
    review_count: 0,
    is_active: false,
    created_at: '2026-05-01T00:00:00Z',
    updated_at: '2026-05-30T00:00:00Z',
  },
]

export const mockReviews: Review[] = []
